---
- name: Setup dotfiles
  hosts: local
  gather_facts: true

  roles:
    - { role: zsh, tags: ['zsh'] }
    - { role: starship, tags: ['starship'] }
    - { role: zellij, tags: ['zellij'] }
    - { role: yazi, tags: ['yazi'] }
#    - { role: lazygit, tags: ['lazygit'] }
    - { role: claude, tags: ['claude'] }
    - { role: codex, tags: ['codex'] }
    - { role: gemini, tags: ['gemini'] }
